config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    resources :tours, only: [:index]
    resources :series, only: [:index, :show] do
      collection do
        get 'country_list'
        get 'itinerary_list'
      end
    end
    
    namespace :v1 do
      resources :flights, only: [:index, :show] do
        member do
          post 'create_booking'
        end
        collection do
          get 'bookings'
        end
      end
      resources :activities, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :hotels, only: [:index, :show] do
        collection do
          get 'cities'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'room_policy'
        end
      end
      resources :wifis, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :series, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'itinerary_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          patch 'update_bookings'
          get 'new_payment'
          post 'create_payment'
          post 'create_insurance_export'
        end
      end

      resources :land_tours, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'land_tours_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'new_payment'
          post 'create_payment'
        end
      end

      resources :payments, only: [:show] do
        collection do
          get 'payment_method'
        end
      end

      resources :users, only:[:none] do
        collection do
          get 'details'
          get 'credit_usage'
          get 'credit_packages'
        end
        member do
          post 'purchase_credits'
        end
      end
      
    end

    namespace :tbo_holidays do
      get 'cities' => 'cities#index'
    end
  end

  namespace :admin do
    root to: "sites#dashboard"
    get   '/dashboard'        => 'sites#dashboard', as: :dashboard
    match '/setting_cover'       => 'sites#cover', as: :cover, via: [:get, :post, :delete]

    resources :users, except: [:destroy] do
      member do
        get 'reset_password'
        post 'reset_password'
        get 'edit_password'
        patch 'update_password'
        get 'topup_credits'
        post 'topup_credits'
      end
      collection do
        get 'access_log'
        get 'online_list'
      end
    end

    resources :flight_commissions, except: [:destroy] do
    end

    resources :tour_leaders, expect: [:destroy] do
    end

    resources :tours, except: [:destroy] do
      member do
        post 'create_booking'
        post 'duplicate'
        get 'insurance'
        get 'booking_rooms'
        get 'edit_booking_rooms'
        get 'confirmation'
        patch 'update_booking_rooms'
      end
      collection do
        get 'uncertainty'
        get 'calendar'
      end

    end

    resources :holiday_calendars, except: [:destroy] do 
    end

    resources :flight_booking_groups, only: [:index, :show] do
    end

    resources :hotels, except: [:destroy]

    resources :tbo_hotels, except: [:destroy] do
      member do
        post 'activate'
        post 'deactivate'
      end
    end

    resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:index, :show]

    resources :tbo_bookings, path: 'tbo_bookings', only: [:index, :show] do
      resource :amendment_request, module: :tbo_bookings do
        member do
          post 'widthraw'
        end
      end
      member do
        post 'cancel'
      end
    end

    resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    end

    resources :itineraries do
      member do
        post 'tour_summary'
        post 'duplicate'
      end
      collection do
        get 'tour_status'
      end
    end

    resources :settings do
      collection do
        get 'travelb2b'
        get 'edit_travelb2b'
        post 'update_travelb2b'
      end
    end

    resources :sliders do
    end

    resources :departments, except: [:destroy] do
    end

    resources :etravel_invoices, only: [:index] do
    end
    
    resources :fairs, except: [:destroy] do
    end

    resources :holidays, except: [:destroy] do
    end

    resources :credit_refunds, except: [:destroy] do
      member do
        post 'update_status'
      end
    end

    resources :booking_groups, only: [:index, :show, :edit, :update] do
      member do
        get  'new_alter'
        post 'create_alter'
        get  'new_export'
        post 'create_export'
        post 'create_insurance_export'
        post 'create_insurance_endorse'
        post 'proforma_invoice'
        post 'assign_agent'
      end
      collection do
        get 'received_deposit'
        get 'tour_booking_summary'
        get 'booking_statistic'
        get 'sales_statistic'
        get 'insurance_changes'
      end
    end

    resources :booking_alterations, only: [:index, :show] do
      member do
        get 'restore'
      end
    end

    resources :invoices, only: [:index, :show] do
    end

    get  'search/fair-tag'                => 'sites#fair_tag'
    get  'search/itinerary-tag'           => 'sites#itinerary_tag'
    get  'search/tour-tag'                => 'sites#tour_tag'
    get  'search/user-tag'                => 'sites#user_tag'
    get  'search/country-tag'             => 'sites#country_tag'

    resources :gifts do
      collection do
        get 'gift_stock_report'
      end
    end

    resources :insurance_rebates, only: [:index, :show, :edit, :update] do
    end

    resources :pre_commisions, except: [:destroy] do
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :gift_tracking_groups, except: [:destroy] do
      collection do
        get 'tracking_summary'
      end
      member do
        get 'summary_detail/:id', to: 'gift_tracking_groups#summary_detail', as: 'summary_detail'
        post 'deliver'
      end
    end

    resources :globaltix_tickets do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
    end

    resources :globaltix_attractions do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        # get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
      member do
        post 'add_ticket'
      end
    end

    resources :exchange_rates, except: [:destroy] do
    end

    resources :roamingman_packages, except: [:destroy] do
      member do
        get 'new_booking'
        post 'create_booking'
      end
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :airlines, except: [:destroy] do
    end

    resources :activities, except: [:destroy] do
    end

    resources :flight_inventories, except: [:destroy] do
    end

    resources :activity_booking_groups, except: [:destroy] do
    end

    resources :land_tours, except: [:destroy] do
    end

    resources :cities, except: [:destroy] do
    end

    resources :land_tour_booking_groups, except: [:destroy] do
      member do
        get 'resend_confirmation'
        get  'new_withdraw'
        post 'create_withdraw'
        get 'voucher'
      end
    end
  end

  resources :gift_tracking_groups, except: [:destroy] do
    member do
      post 'submit'
      post 'acknowledge'
      post 'reject'
    end
  end

  resources :hotels, path: 'hotels', only: [:index] do
    collection do
      get   'details'
      get   'booking'
      post  'booking'
    end
  end

  resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:create] do
    member do
      post  'cancel'
    end
  end

  resources :flights, only: [:index, :show] do
    member do
      post 'create_booking'
    end
    collection do
      get 'thankyou'
    end
  end

  resources :flight_booking_groups, only: [:index, :show] do
    member do
      get 'invoice'
    end
  end

  # resources :activities, only: [:index, :show, :create] do
    # resources :activity_bookings, only: [:new, :create] do
    # end

    # collection do
    #   get 'new_booking/:id', to: 'activities#new_booking', as: 'new_booking'
    #   post 'create_booking'
    # end
  # end

  resources :activity_booking_groups, only: [:show, :edit, :update, :index] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :payments, only: [:index] do
    collection do
      get 'error_page'
    end
  end
  
  resources :itineraries do
  end

  resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :roamingman_packages, only: [:index, :show] do
    resources :roamingman_bookings, only: [:new, :create] do
    end
  end

  resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

app/models/activity_booking_group.rb
class ActivityBookingGroup < ApplicationRecord
  include ActivityValidator

  belongs_to :last_edited_user, class_name: "User", optional: true
  has_one :payment, as: :taggable
  has_many :etravel_invoices, as: :taggable
  has_many :activity_bookings, -> { order("id") }
  accepts_nested_attributes_for :activity_bookings, allow_destroy: true

  enum payment_method: [:online, :offline]

  scope :in_between, ->(inverval) { where(created_at:(inverval))}

  validates_associated :activity_bookings
  validates_with FpxAmountValidator

  def activity
    if activity_bookings.present?
      activity_bookings.first.activity
    else
      nil
    end
  end

  def reference_id
    "#{self.id.to_s.rjust(10, '0')}A"
  end

  def booking_ref
    if activity_bookings.present?
      activity_bookings.map { |e| e.code }.join(', ')
    else
      ""
    end
  end

  def product_name
    if activity_bookings.first.activity.present?
      activity_bookings.first.activity.title
    else
      ""
    end
  end

  def product_description
    "Ice Holidays Activity Booking"
  end

  def booking_quantity
    if activity_bookings.present?
      activity_bookings.count
    else
      0
    end
  end

  def buyer_email
    if activity_bookings.first.agent_user.present?
      activity_bookings.first.agent_user.email
    else
      ""
    end
  end

  def total_quantity
    activity_bookings.map(&:quantity).inject(:+)
  end

  # def total_price
  #   activity_bookings.first.price
  # end

  def calculate_qty(category)
    booking = activity_bookings.select { |p| p.category == category }.first 
    if booking.present? 
      booking.quantity 
    else
      0
    end
  end

  def unit_price(category)
    activity_bookings.select { |p| p.category == category }.first
  end

  def redirect_url
    Rails.application.routes.url_helpers.thank_you_activity_booking_groups_path(:id => self.id)
  end

  def show_url
    Rails.application.routes.url_helpers.activity_booking_group_path(:id => self.id)
  end

  def agent_user
    if activity_bookings.present?
      activity_bookings.first.agent_user
    else
      nil
    end
  end

  def send_notify
    agent = self.agent_user
    if agent.present?
      if agent.emails.present?
        ActivityMailer.notify(agent, self, agent.emails.join(', ')).deliver_now
        if self.has_payment?
          ActivityMailer.receipt(agent, self, agent.emails.join(', ')).deliver_now
        end
      end
      ActivityMailer.notify_admin(agent, self).deliver_now
    end
  end

  def has_payment?
    # self.payments.paid.map(&:amount).inject(:+) >= 1
    self.payment.paid? && self.payment.amount >= 1
  end

  def ref_no
    "BACT#{self.id.to_s.rjust(9, '0')}"
  end

end

app/controllers/activity_booking_groups_controller.rb
class ActivityBookingGroupsController < ApplicationController
  def index
    authorize ActivityBookingGroup

    @today = DateTime.current
    if params[:begin].present? && params[:end].present?
      interval = "#{params[:begin]}".in_time_zone.beginning_of_day.."#{params[:end]}".in_time_zone.end_of_day
    elsif params[:begin].present?
      interval = "#{params[:begin]}".in_time_zone.beginning_of_day...DateTime::Infinity.new
    elsif params[:end].present?
      interval = DateTime.new.."#{params[:end]}".in_time_zone.end_of_day
    else
      interval = DateTime::Infinity.new...DateTime::Infinity.new
    end

    @activity_booking_groups = current_user.activity_booking_groups.includes(activity_bookings: [:agent_user]).in_between(interval).order("activity_booking_groups.created_at desc").page(params[:page]).per(30)
  end

  def show
    @activity_booking_group = current_user.activity_booking_groups.find(params[:id])
    @activity_booking = @activity_booking_group.activity_bookings.first
    authorize @activity_booking_group
  end

  def edit
    @activity_booking_group = current_user.activity_booking_groups.find(params[:id])
    @activity_booking = @activity_booking_group.activity_bookings.first
    authorize @activity_booking_group
  end

  def update
    @activity_booking_group = current_user.activity_booking_groups.find(params[:id])
    authorize @activity_booking_group
    @activity_booking_group.assign_attributes(update_booking_group_params)

    if @activity_booking_group.save
      redirect_to activity_booking_group_path(@activity_booking_group), notice: 'All bookings was successfully updated.'
    else
      render :edit
    end
  end

  def thank_you
    @activity_booking_group = current_user.activity_booking_groups.find(params[:id])
    @activity_booking = @activity_booking_group.activity_bookings.first
  end

  def invoice
    # @activity_booking_group = current_user.activity_booking_groups.find(params[:id])
    @activity_booking_group = ActivityBookingGroup.find(params[:id])
    authorize @activity_booking_group
    @activity_bookings = @activity_booking_group.activity_bookings.includes(:agent_user)
  end

private
  def update_booking_group_params
    new_params = params.require(:activity_booking_group).permit(:travel_date, activity_bookings_attributes: [:id, :name, :mobile, :email, :remark, :_destroy])
    if new_params[:activity_bookings_attributes].present?
      new_params[:activity_bookings_attributes].each {|k,v| v.merge!(last_edited_user_id: current_user.id)}
    end
    new_params.merge(last_edited_user_id: current_user.id)
  end
end

app/controllers/admin/activity_booking_groups_controller.rb
class Admin::ActivityBookingGroupsController < AdminController
  before_action :check_auth

  def index
    @today = DateTime.current
    if params[:begin].present? && params[:end].present?
      interval = "#{params[:begin]}".in_time_zone.beginning_of_day.."#{params[:end]}".in_time_zone.end_of_day
    elsif params[:begin].present?
      interval = "#{params[:begin]}".in_time_zone.beginning_of_day...DateTime::Infinity.new
    elsif params[:end].present?
      interval = DateTime.new.."#{params[:end]}".in_time_zone.end_of_day
    else
      interval = DateTime::Infinity.new...DateTime::Infinity.new
    end

    @activity_booking_groups = ActivityBookingGroup.in_between(interval).order("activity_booking_groups.created_at desc").page(params[:page]).per(50)
  end

  def show
    @activity_booking_group = ActivityBookingGroup.includes(:activity_bookings).find(params[:id])
    @activity_booking = @activity_booking_group.activity_bookings.first
  end

  def edit
    @activity_booking_group = ActivityBookingGroup.includes(:activity_bookings).find(params[:id])
    @activity_booking = @activity_booking_group.activity_bookings.first
  end

  def update
    @activity_booking_group = ActivityBookingGroup.find(params[:id])
    @activity_booking_group.assign_attributes(update_booking_group_params)

    if @activity_booking_group.save
      redirect_to admin_activity_booking_group_path(@activity_booking_group), notice: 'All bookings was successfully updated.'
    else
      render :edit
    end
  end

private
  def update_booking_group_params
    new_params = params.require(:activity_booking_group).permit(:travel_date, activity_bookings_attributes: [:id, :name, :mobile, :email, :remark, :_destroy])
    if new_params[:activity_bookings_attributes].present?
      new_params[:activity_bookings_attributes].each {|k,v| v.merge!(last_edited_user_id: current_user.id)}
    end
    new_params.merge(last_edited_user_id: current_user.id)
  end

  def check_auth
    authorize ActivityBookingGroup
  end
end

app/views/activity_booking_groups/_activity_booking_fields.html.erb
<div class="nested-fields">
  <div class='custom-form-group form-group col-sm-4'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'custom-form-control form-control' %>
  </div>
  <div class='custom-form-group form-group col-sm-4'>
    <%= f.label :mobile %>
    <%= f.text_field :mobile, class: 'custom-form-control form-control' %>
  </div>
  <div class='custom-form-group form-group col-sm-4'>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'custom-form-control form-control' %>
  </div>
  <div class='custom-form-group form-group col-sm-12'>
    <%= f.label :remark %>
    <%= f.text_field :remark, class: 'custom-form-control form-control activity_quantity' %>
  </div>
</div>

app/views/activity_booking_groups/index.html.erb
<% content_for :head do %>
  <title><%= Rails.application.secrets.app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-puzzle-piece fa-fw"></i>Activity Bookings
<% end %>

<%= render 'shared/single_panel', card_title: 'Activity Booking List' do %>
  <%= link_to('Globaltix Bookings', globaltix_ticket_booking_groups_path, class: 'btn btn-primary')%>
  <div class="row">
    <div class="col-xs-12 mt20">
      <%= link_to('Today', activity_booking_groups_path(begin: @today.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Yesterday', activity_booking_groups_path(begin: (@today - 1.day).strftime("%F"), end: (@today - 1.day).strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Current Week', activity_booking_groups_path(begin: @today.beginning_of_week.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Week', activity_booking_groups_path(begin: @today.last_week.beginning_of_week.strftime("%F"), end: @today.last_week.end_of_week.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Week To Now', activity_booking_groups_path(begin: @today.last_week.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Current Month', activity_booking_groups_path(begin: @today.beginning_of_month.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Month', activity_booking_groups_path(begin: @today.last_month.beginning_of_month.strftime("%F"), end: @today.last_month.end_of_month.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Month To Now', activity_booking_groups_path(begin: @today.last_month.beginning_of_month.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Current Year', activity_booking_groups_path(begin: @today.beginning_of_year.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Year', activity_booking_groups_path(begin: @today.last_year.beginning_of_year.strftime("%F"), end: @today.last_year.end_of_year.strftime("%F")), class: 'btn btn-default') %>
      <%= link_to('Last Year To Now', activity_booking_groups_path(begin: @today.last_year.beginning_of_year.strftime("%F")), class: 'btn btn-default') %>

    </div>
    <div class="col-xs-12 mt20 mb20">
      <%= form_tag activity_booking_groups_path, method: 'get' do %>
        From <%= date_field_tag :begin, params[:begin] %> To <%= date_field_tag :end, params[:end] %><br>
        <%= submit_tag 'Search', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="table-responsive mt20">
      <table class="table table-bordered table-condensed">
        <thead>
          <tr>
            <th>Ref</th>
            <th>Name</th>
            <th>Activity</th>
            <th>Quantity</th>
            <th>Total Price (MYR)</th>
            <th>Payment Method</th>
            <th>Payment Status</th>
            <th>Remark</th>
            <th>Booked At</th>
          </tr>
        </thead>
        <tbody>
          <% @activity_booking_groups.each_with_index do |group, i| %>
            <tr >
              <td><%= link_to group.activity_bookings.first.code, activity_booking_group_path(group) %></td>
              <td><%= group.activity_bookings.first.name %></td>
              <td><%= group.activity.title %></td>
              <td><%= group.total_quantity %></td>
              <td><%= group.price %></td>
              <td><%= group.payment.present? ? group.payment.gateway_text : '' %></td>
              <td><%= group.payment.present? ? group.payment.status.humanize : '' %></td>
              <td><%= group.activity_bookings.first.remark.present? ? group.activity_bookings.first.remark.humanize : '' %></td>
              <td><%= group.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>
  <%= paginate @activity_booking_groups if @activity_booking_groups.present? %>
<% end %>

app/views/activity_booking_groups/show.html.erb
<% content_for :head do %>
  <title><%= Rails.application.secrets.app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-puzzle-piece fa-fw"></i>Activity Booking
<% end %>

<%= render 'shared/single_panel', card_title: 'Activity Booking Details' do %>
  <div class="row">
    <div class="custom-form-group form-group col-sm-12">
      <h4><%= @activity_booking_group.activity.title.present? ? @activity_booking_group.activity.title : "Untitled" %></h4>
    </div>
    
    <div class="col-sm-12 cover-div">
      <div id="cover-slick">
        <% @activity_booking_group.activity.covers.each do |cover| %>
          <% if cover.image.present? %>
            <div class="custom-form-group form-group col-sm-12">
              <%= link_to "" do %>
                <% image_tag cover.image.url, class: 'cover-activity' %>
              <% end %>
            </div>  
          <% end %>
        <% end %>
      </div>
    </div>
    <% if @activity_booking_group.activity.highlight.present? %>
      <div class="custom-form-group form-group col-sm-12">
        <%= label_tag '', "Highlight" %><br>
        <%= @activity_booking_group.activity.highlight %>
      </div>
    <% end %>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Destination" %><br>
      <%= @activity_booking_group.activity.country %>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Operation Days" %><br>
      <%= @activity_booking_group.activity.join_operation_days %>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Description" %><br>
      <%= simple_format(@activity_booking_group.activity.description) %>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Terms and Conditions" %><br>
      <%= simple_format(@activity_booking_group.activity.terms_and_conditions) %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <%= label_tag '', "Travel Date" %>
    </div> 
    <div class="col-sm-4">
      <%= text_field_tag '', @activity_booking_group.travel_date.try(:strftime, "%d/%m/%Y"), class: 'custom-form-control form-control', disabled: true %>
    </div>  
    <div class="col-sm-6">
      &nbsp;
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "No of Package(s)" %><br>
      <% @activity_booking_group.activity.activity_prices.each do |price| %>
        <div class="field custom-form-group form-group col-sm-2">
          <%= label_tag '', "#{price.category}", class: 'custom-form-control' %>
        </div>  
        <div class="field custom-form-group form-group col-sm-1">
          <%= text_field_tag '', @activity_booking_group.calculate_qty(price.category), class: 'custom-form-control form-control', disabled: true %>
        </div> 
        <div class="field custom-form-group form-group col-sm-9">
          <p class="custom-form-control">x MYR <%= @activity_booking_group.unit_price(price.category).present? ? @activity_booking_group.unit_price(price.category).price : price.price %></p>
        </div>
      <% end %>
      <div class="field custom-form-group form-group col-sm-2">
        <%= label_tag '', "Total Amount", class: 'custom-form-control' %>
      </div>  
      <div class="field custom-form-group form-group col-sm-2">
        <p class="custom-form-control bold" id="total-amount">MYR <%= @activity_booking_group.price %></p>
      </div> 
      <div class="field custom-form-group form-group col-sm-8">
        &nbsp;
      </div>
    </div>
  </div>

  <div class="row">
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Traveller Details" %>
      <div class="nested-fields">
        <div class="field custom-form-group form-group col-sm-4">
          <%= label_tag :name %>
          <%= text_field_tag '', @activity_booking.name, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-4">
          <%= label_tag :mobile %>
          <%= text_field_tag '', @activity_booking.mobile, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-4">
          <%= label_tag :email %>
          <%= text_field_tag '', @activity_booking.email, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-12">
          <%= label_tag :remark %>
          <%= text_field_tag '', @activity_booking.remark, class: 'custom-form-control form-control', disabled: true %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Payment Type" %>
      <div class="nested-fields">
        <div class="custom-form-group form-group col-sm-2">
          <%= label_tag :payment_method %>
          <%= text_field_tag '', @activity_booking_group.payment_method.present? ? @activity_booking_group.payment_method.humanize : '', class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-3">
          <%= label_tag :gateway %>
          <%= text_field_tag '', @activity_booking_group.payment.gateway.humanize, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-3">
          <%= label_tag :transaction_no %>
          <%= text_field_tag '', @activity_booking_group.payment.transaction_no, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="field custom-form-group form-group col-sm-2">
          <%= label_tag :method %>
          <%= text_field_tag '', @activity_booking_group.payment.get_method, class: 'custom-form-control form-control', disabled: true %>
        </div>
        <div class="custom-form-group form-group col-sm-2">
          <%= label_tag :payment_status %>
          <%= text_field_tag '', @activity_booking_group.payment.present? ? @activity_booking_group.payment.status.humanize : 'Pending', class: 'custom-form-control form-control', disabled: true %>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_activity_booking_group_path(@activity_booking_group), class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn' %>
<% end %>