config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    resources :tours, only: [:index]
    resources :series, only: [:index, :show] do
      collection do
        get 'country_list'
        get 'itinerary_list'
      end
    end
    
    namespace :v1 do
      resources :flights, only: [:index, :show] do
        member do
          post 'create_booking'
        end
        collection do
          get 'bookings'
        end
      end
      resources :activities, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :hotels, only: [:index, :show] do
        collection do
          get 'cities'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'room_policy'
        end
      end
      resources :wifis, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :series, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'itinerary_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          patch 'update_bookings'
          get 'new_payment'
          post 'create_payment'
          post 'create_insurance_export'
        end
      end

      resources :land_tours, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'land_tours_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'new_payment'
          post 'create_payment'
        end
      end

      resources :payments, only: [:show] do
        collection do
          get 'payment_method'
        end
      end

      resources :users, only:[:none] do
        collection do
          get 'details'
          get 'credit_usage'
          get 'credit_packages'
        end
        member do
          post 'purchase_credits'
        end
      end
      
    end

    namespace :tbo_holidays do
      get 'cities' => 'cities#index'
    end
  end

  namespace :admin do
    root to: "sites#dashboard"
    get   '/dashboard'        => 'sites#dashboard', as: :dashboard
    match '/setting_cover'       => 'sites#cover', as: :cover, via: [:get, :post, :delete]

    resources :users, except: [:destroy] do
      member do
        get 'reset_password'
        post 'reset_password'
        get 'edit_password'
        patch 'update_password'
        get 'topup_credits'
        post 'topup_credits'
      end
      collection do
        get 'access_log'
        get 'online_list'
      end
    end

    resources :flight_commissions, except: [:destroy] do
    end

    resources :tour_leaders, expect: [:destroy] do
    end

    resources :tours, except: [:destroy] do
      member do
        post 'create_booking'
        post 'duplicate'
        get 'insurance'
        get 'booking_rooms'
        get 'edit_booking_rooms'
        get 'confirmation'
        patch 'update_booking_rooms'
      end
      collection do
        get 'uncertainty'
        get 'calendar'
      end

    end

    resources :holiday_calendars, except: [:destroy] do 
    end

    resources :flight_booking_groups, only: [:index, :show] do
    end

    resources :hotels, except: [:destroy]

    resources :tbo_hotels, except: [:destroy] do
      member do
        post 'activate'
        post 'deactivate'
      end
    end

    resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:index, :show]

    resources :tbo_bookings, path: 'tbo_bookings', only: [:index, :show] do
      resource :amendment_request, module: :tbo_bookings do
        member do
          post 'widthraw'
        end
      end
      member do
        post 'cancel'
      end
    end

    resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    end

    resources :itineraries do
      member do
        post 'tour_summary'
        post 'duplicate'
      end
      collection do
        get 'tour_status'
      end
    end

    resources :settings do
      collection do
        get 'travelb2b'
        get 'edit_travelb2b'
        post 'update_travelb2b'
      end
    end

    resources :sliders do
    end

    resources :departments, except: [:destroy] do
    end

    resources :etravel_invoices, only: [:index] do
    end
    
    resources :fairs, except: [:destroy] do
    end

    resources :holidays, except: [:destroy] do
    end

    resources :credit_refunds, except: [:destroy] do
      member do
        post 'update_status'
      end
    end

    resources :booking_groups, only: [:index, :show, :edit, :update] do
      member do
        get  'new_alter'
        post 'create_alter'
        get  'new_export'
        post 'create_export'
        post 'create_insurance_export'
        post 'create_insurance_endorse'
        post 'proforma_invoice'
        post 'assign_agent'
      end
      collection do
        get 'received_deposit'
        get 'tour_booking_summary'
        get 'booking_statistic'
        get 'sales_statistic'
        get 'insurance_changes'
      end
    end

    resources :booking_alterations, only: [:index, :show] do
      member do
        get 'restore'
      end
    end

    resources :invoices, only: [:index, :show] do
    end

    get  'search/fair-tag'                => 'sites#fair_tag'
    get  'search/itinerary-tag'           => 'sites#itinerary_tag'
    get  'search/tour-tag'                => 'sites#tour_tag'
    get  'search/user-tag'                => 'sites#user_tag'
    get  'search/country-tag'             => 'sites#country_tag'

    resources :gifts do
      collection do
        get 'gift_stock_report'
      end
    end

    resources :insurance_rebates, only: [:index, :show, :edit, :update] do
    end

    resources :pre_commisions, except: [:destroy] do
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :gift_tracking_groups, except: [:destroy] do
      collection do
        get 'tracking_summary'
      end
      member do
        get 'summary_detail/:id', to: 'gift_tracking_groups#summary_detail', as: 'summary_detail'
        post 'deliver'
      end
    end

    resources :globaltix_tickets do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
    end

    resources :globaltix_attractions do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        # get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
      member do
        post 'add_ticket'
      end
    end

    resources :exchange_rates, except: [:destroy] do
    end

    resources :roamingman_packages, except: [:destroy] do
      member do
        get 'new_booking'
        post 'create_booking'
      end
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :airlines, except: [:destroy] do
    end

    resources :activities, except: [:destroy] do
    end

    resources :flight_inventories, except: [:destroy] do
    end

    resources :activity_booking_groups, except: [:destroy] do
    end

    resources :land_tours, except: [:destroy] do
    end

    resources :cities, except: [:destroy] do
    end

    resources :land_tour_booking_groups, except: [:destroy] do
      member do
        get 'resend_confirmation'
        get  'new_withdraw'
        post 'create_withdraw'
        get 'voucher'
      end
    end
  end

  resources :gift_tracking_groups, except: [:destroy] do
    member do
      post 'submit'
      post 'acknowledge'
      post 'reject'
    end
  end

  resources :hotels, path: 'hotels', only: [:index] do
    collection do
      get   'details'
      get   'booking'
      post  'booking'
    end
  end

  resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:create] do
    member do
      post  'cancel'
    end
  end

  resources :flights, only: [:index, :show] do
    member do
      post 'create_booking'
    end
    collection do
      get 'thankyou'
    end
  end

  resources :flight_booking_groups, only: [:index, :show] do
    member do
      get 'invoice'
    end
  end

  # resources :activities, only: [:index, :show, :create] do
    # resources :activity_bookings, only: [:new, :create] do
    # end

    # collection do
    #   get 'new_booking/:id', to: 'activities#new_booking', as: 'new_booking'
    #   post 'create_booking'
    # end
  # end

  resources :activity_booking_groups, only: [:show, :edit, :update, :index] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :payments, only: [:index] do
    collection do
      get 'error_page'
    end
  end
  
  resources :itineraries do
  end

  resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :roamingman_packages, only: [:index, :show] do
    resources :roamingman_bookings, only: [:new, :create] do
    end
  end

  resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

app/controllers/api/tours_controller.rb
module Api
  class ToursController < ApiController

    def index
      respond_to do |format|
        format.json do
          if params[:key].present? && params[:key] == 'GDApiYEK'
            destination = params[:destination].present? ? params[:destination] : ''
            caption = params[:caption].present? ? params[:caption] : ''
            code = params[:code].present? ? params[:code] : ''
            category = params[:category].present? ? params[:category] : ''
            keyword = params[:keyword].present? ? params[:keyword] : ''
            caption_uniq = params[:caption_uniq].present? ? true : false
            only_departure_date = params[:only_departure_date].present? ? true : false
            only_bookable = params[:only_bookable].present? ? true : false

            if params[:end].present? && "#{params[:end]}".in_time_zone
              date_range = Date.tomorrow.."#{params[:end]}".in_time_zone.end_of_day
            else
              date_range = Date.tomorrow...DateTime::Infinity.new
            end

            if params[:departure_date_start].present? && "#{params[:departure_date_start]}".in_time_zone
              departure_date_start = "#{params[:departure_date_start]}".in_time_zone.beginning_of_day
            else
              departure_date_start = Date.tomorrow
            end

            if params[:departure_date_end].present? && "#{params[:departure_date_end]}".in_time_zone
              departure_date_end = "#{params[:departure_date_end]}".in_time_zone.end_of_day
            else
              departure_date_end = DateTime::Infinity.new
            end

            if params[:page].present?
              page = params[:page]
            else
              page = 1
            end

            if params[:limit].present?
              limit = params[:limit]
            else
              limit = 1000
            end

            departure_date_interval = departure_date_start...departure_date_end

            
            if caption_uniq
              if only_bookable
                @tours = Tour.visible.caption_uniq.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).bookable(date_range).in_between_departure(departure_date_interval).page(page).per(limit)
              else
                @tours = Tour.visible.caption_uniq.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).in_between_departure(departure_date_interval).page(page).per(limit)
              end
            elsif only_departure_date
              if only_bookable
                departure_dates = Tour.visible.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).bookable(date_range).in_between_departure(departure_date_interval).order(:departure_date).pluck(:departure_date).uniq
              else
                departure_dates = Tour.visible.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).in_between_departure(departure_date_interval).order(:departure_date).pluck(:departure_date).uniq
              end
              render json: { departure_dates: departure_dates.map{|d| d.strftime("%F")} }
            else
              if only_bookable
                @tours = Tour.visible.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).bookable(date_range).in_between_departure(departure_date_interval).order(:departure_date, :code).page(page).per(limit)
              else
                @tours = Tour.visible.search(keyword).destination(destination).where("tours.code ILIKE ?", "%#{code}%").category_filter(category).caption(caption).in_between_departure(departure_date_interval).order(:departure_date, :code).page(page).per(limit)
              end
            end
          else
            render json: { ret: "Failed" }, status: 401
          end
        end
      end
    end
    
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :check_auth

  def index
    @today = Date.today
    keywords = params[:keywords].present? ? params[:keywords] : ''

    if params[:begin].present?
      interval_start = "#{params[:begin]}".in_time_zone
      if interval_start < (@today+1.day)
        interval_start = (@today+1.day).beginning_of_day
      end
    else
      interval_start = (@today+1.day).beginning_of_day
    end

    if params[:end].present?
      interval_end = "#{params[:end]}".in_time_zone.end_of_day
    else
      interval_end = DateTime::Infinity.new
    end

    interval = interval_start..interval_end
    contient_country = params[:contient_country].present? ? params[:contient_country] : ''

    if params[:bookable].present? && params[:bookable] == 'false'
      @tours = Tour.visible.brand_filter(params[:brand]).search(keywords).destination(contient_country).in_between_departure(interval).page(params[:page]).per(Tour::TOURS_PER_PAGE).order(:departure_date, :code)
    else
      @tours = Tour.visible.brand_filter(params[:brand]).search(keywords).destination(contient_country).bookable(interval).page(params[:page]).per(Tour::TOURS_PER_PAGE).order(:departure_date, :code)
    end
  end

  def show
    if current_user.able_access_admin_dashboard?
      @tour = Tour.find(params[:id])
    else
      @tour = Tour.find(params[:id])
    end
    @bookings = @tour.bookings.visible.agent_user(current_user).order(:id)
    if params[:expired].present?
      flash[:error] = "The remaining booking time was expired, please book again. Sorry for inconvenient."
    end
  end

private
  def check_auth
    authorize Tour, :index?
  end

end

app/views/admin/tours/_single_booking_room_fields.html.erb
  <div class="nested-fields">
    <div class="custom-form-group form-group col-sm-12">
      <%= f.label :single_room %>
      <%= f.hidden_field :room_type, value: 'single_room' %>
      <div class="custom-form-group form-group col-sm-12">
        <%= f.fields_for :bookings do |booking| %>
          <div class="custom-form-group form-group col-sm-3">
            <label>Select Guest 1</label>
            <%= render_booking_room_selection(f, booking, 1, @booking_adult_child_twin, @tour.tour_leader) %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= link_to_remove_association "Remove room", f %>
    </div>
</div>

app/views/admin/tours/cut_off.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-globe fa-fw"></i>Tour Calendar
<% end %>

<%= render 'shared/single_panel', card_title: 'Cut Off Tours Calendar' do %>
  <%= link_to('View All Tours', admin_tours_path, class: 'btn btn-primary')%>
  <%= link_to 'Insurance Calendar', calendar_admin_tours_path(insurance: true), class: 'btn btn-warning' %>
  <br><br>
  <div class="row">
    <div class="col-xs-12 mt20 mb20">
      <%= form_tag calendar_admin_tours_path, method: 'get' do %>
        <%= hidden_field_tag :cut_off, 'true' %>
        From <%= date_field_tag :begin, params[:begin] %> To <%= date_field_tag :end, params[:end] %>
        <%= submit_tag 'Search', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <%= month_calendar attribute: :cut_off_start, events: @tours do |date, tours| %>
    <strong><h5><%= date.strftime("%d %^b %Y") %></h5></strong>

    <% tours.sort_by { |p| p.code }.each do |tour| %>
      <div>
        <div class="trim cut-off" data-toggle="tooltip" data-placement="top" title="<%= tour.code %>"><%= tour.code %></div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/admin/tours/edit_booking_rooms.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-bed fa-fw"></i> Booking Rooms
<% end %>

<%= render 'shared/single_panel', card_title: 'Edit Booking Rooms' do %>
  <%= form_for [:admin, @tour], html: { role: "form" }, url: { action: "update_booking_rooms", method: "post" } do |f| %>
    <div class="row" id="booking_room_form">

      <div class="custom-form-group form-group col-sm-12">
        <h3>Single Room</h3>
        <hr />
        <% f.object.booking_rooms.where(room_type: :single_room) %>
        <%= f.fields_for :booking_rooms, @tour.booking_rooms.where(room_type: :single_room) do |br| %>
          <div class="custom-form-group form-group col-sm-12 booking-group-form">
            <%= render 'single_booking_room_fields', f: br %>
          </div>
        <% end %>

        <div class="custom-form-group form-group col-sm-12">
          <%= link_to_add_association 'Add single room', f, :booking_rooms, partial: 'single_booking_room_fields', class: 'btn btn-warning', id: 'add_single_room' %>
        </div>
      </div>

      <div class="custom-form-group form-group col-sm-12">
        <h3>Double Room</h3>
        <hr />
        <% f.object.booking_rooms.where(room_type: :double_room) %>
        <%= f.fields_for :booking_rooms, @tour.booking_rooms.where(room_type: :double_room) do |br| %>
          <div class="custom-form-group form-group col-sm-12 booking-group-form">
            <%= render 'double_booking_room_fields', f: br %>
          </div>
        <% end %>

        <div class="custom-form-group form-group col-sm-12">
          <%= link_to_add_association 'Add double room', f, :booking_rooms, partial: 'double_booking_room_fields', class: 'btn btn-warning', id: 'add_double_room' %>
        </div>
      </div>

      <div class="custom-form-group form-group col-sm-12">
        <h3>Twin Room</h3>
        <hr />
        <% f.object.booking_rooms.where(room_type: :twin_room) %>
        <%= f.fields_for :booking_rooms, @tour.booking_rooms.where(room_type: :twin_room) do |br| %>
          <div class="custom-form-group form-group col-sm-12 booking-group-form">
            <%= render 'twin_booking_room_fields', f: br %>
          </div>
        <% end %>
        
        <div class="custom-form-group form-group col-sm-12">
          <%= link_to_add_association 'Add twin room', f, :booking_rooms, partial: 'twin_booking_room_fields', class: 'btn btn-warning', id: 'add_twin_room' %>
        </div>
      </div>

      <div class="custom-form-group form-group col-sm-12">
        <h3>Triple Room</h3>
        <hr />
        <% f.object.booking_rooms.where(room_type: :triple_room) %>
        <%= f.fields_for :booking_rooms, @tour.booking_rooms.where(room_type: :triple_room) do |br| %>
          <div class="custom-form-group form-group col-sm-12 booking-group-form">
            <%= render 'triple_booking_room_fields', f: br %>
          </div>
        <% end %>
        
        <div class="custom-form-group form-group col-sm-12">
          <%= link_to_add_association 'Add triple room', f, :booking_rooms, partial: 'triple_booking_room_fields', class: 'btn btn-warning', id: 'add_triple_room' %>
        </div>
      </div>

      <div class="col-sm-12">
        <div class="table-responsive mt20 scroll-bar">
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th class="number">#</th>
                <th class="number">Grouping</th>
                <th class="code">Name</th>
                <th>Booked by</th>
                <% if @tour.is_cruise? %>
                  <th>Cruise Room/ID</th>
                <% end %>
                <th>Passport No</th>
                <th>Visa No</th>
                <th class="number">Admin Remark</th>
                <th class="number">Remark</th>
                <th class="number">Rooming Remark</th>
              </tr>
            </thead>
            <tbody>
              <% start_seq = params[:page].present? ? (params[:page].to_i - 1)*Booking::ADMIN_BOOKINGS_PER_PAGE+1 : 1 %>
              <% @tour.bookings.each_with_index do |booking, index| %>
                <tr>
                  <td class="number"><%= index + start_seq %></td>
                  <% if booking.booking_group.exported? %>
                    <td class="expoted_info">
                      <%= link_to booking.booking_group.code, admin_booking_group_path(booking.booking_group), title: booking.booking_group.exported_info %>
                    </td>
                  <% else %>
                    <td>
                      <%= booking.booking_group.code %>
                    </td>
                  <% end %>
                  <td><div class="trim code" data-toggle="tooltip" data-placement="top" title="<%= booking.name %>"><%= booking.name %></div></td>
                  <td><%= booking.booked_by_detail %></td>
                  <td><%= booking.passport_number%></td>  
                  <td><%= booking.visa_no%></td> 
                  <td><div class="trim code" data-toggle="tooltip" data-placement="top" title="<%= booking.admin_remark %>"><%= booking.admin_remark %></div></td>
                  <td>
                    <%= render_insurance_icon(booking) %>
                    <%= render_passport_icon(booking) %>
                    <span class="trim code" data-toggle="tooltip" data-placement="top" title="<%= render_remark_infant_indicator(booking, true) %>"><%= render_remark_infant_indicator(booking) %>
                    </span>
                  </td>
                  <td><%= booking.operator_remark %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    
    <%= f.submit "Update", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', booking_rooms_admin_tour_path(@tour), class: 'btn' %>
  <% end %>
<% end %>

app/views/admin/tours/insurance.html.erb
<% content_for :head do %>
  <title><%= @tour.code %> | <%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-globe fa-fw"></i>Tour Insurance
<% end %>

<%= render 'shared/single_panel', card_title: "Tour Insurance Detail: #{@tour.code}" do %>
  <% if @exported_bookings.present? || @non_exported_bookings.present? %>
    <%= link_to 'Print', insurance_admin_tour_path(@tour, print: true), class: 'btn btn-primary', target: '_blank' %>
  <% else %>
    <h5>There's no insurance information available for this tour.</h5>
  <% end %>

  <% if @exported_bookings.present? %>
    <div class="col-sm-12">
      <div class="table-responsive mt20">
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
              <th colspan="5">Exported Insurance</th>
            </tr>
            <tr>
              <th class="number">No.</th>
              <th class="number">Grouping</th>
              <th>Booked by</th>
              <th class="code">Name</th>
              <th class="number">Insurance Certificate</th>
            </tr>
          </thead>
          <tbody>
            <% @exported_bookings.each_with_index do |booking, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <% if booking.booking_group.exported? %>
                  <td class="expoted_info">
                    <%= link_to booking.booking_group.code, admin_booking_group_path(booking.booking_group), title: booking.booking_group.exported_info %>
                  </td>
                <% else %>
                  <td>
                    <%= link_to booking.booking_group.code, admin_booking_group_path(booking.booking_group) %>
                  </td>
                <% end %>
                <td><%= booking.booked_by_detail %></td>
                <td><div class="trim code" data-toggle="tooltip" data-placement="top" title="<%= booking.name %>"><%= booking.name %></div></td>
                <td><%= link_to booking.policy_number, booking.insurance_cert %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
  <br><br>
  <% if @non_exported_bookings.present? %>
    <div class="col-sm-12">
      <div class="table-responsive mt20">
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
              <th colspan="5">Non-Exported Insurance</th>
            </tr>
            <tr>
              <th class="number">No.</th>
              <th class="number">Grouping</th>
              <th>Booked by</th>
              <th class="code">Name</th>
              <th class="number">Insurance Certificate</th>
            </tr>
          </thead>
          <tbody>
            <% @non_exported_bookings.each_with_index do |booking, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <% if booking.booking_group.exported? %>
                  <td class="expoted_info">
                    <%= link_to booking.booking_group.code, admin_booking_group_path(booking.booking_group), title: booking.booking_group.exported_info %>
                  </td>
                <% else %>
                  <td>
                    <%= link_to booking.booking_group.code, admin_booking_group_path(booking.booking_group) %>
                  </td>
                <% end %>
                <td><%= booking.booked_by_detail %></td>
                <td><div class="trim code" data-toggle="tooltip" data-placement="top" title="<%= booking.name %>"><%= booking.name %></div></td>
                <td></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/tours/uncertainty.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-globe fa-fw"></i>Tours
<% end %>

<% if params[:begin].present? && params[:end].present? %>
  <% card_title = "View Uncertainty Tours: #{params[:begin]} to #{params[:end]}" %>
<% elsif params[:begin].present? %>
  <% card_title = "View Uncertainty Tours: From #{params[:begin]}" %>
<% elsif params[:end].present? %>
  <% card_title = "View Uncertainty Tours: Until #{params[:end]}" %>
<% else %>
  <% card_title = 'View Uncertainty Tours' %>
<% end %>
<%= render 'shared/single_panel', card_title: card_title do %>
  <%= link_to('View All Tours', admin_tours_path, class: 'btn btn-primary')%>
  <div class="row">
    <div class="col-xs-12 mt20 mb20">
      <%= form_tag uncertainty_admin_tours_path, method: 'get' do %>
        From <%= date_field_tag :begin, params[:begin] %> To <%= date_field_tag :end, params[:end] %>
        <%= submit_tag 'Search', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Departure</th>
          <th>D2G</th>
          <th class="code">Code</th>
          <th class="cation">Caption</th>
          <th>Seats(R)</th>
          <th>Booked(R)</th>
          <th>G/Seats</th>
          <th>Shortage</th>
          <th>Remark</th>
        </tr>
      </thead>
      <tbody>
        <% @tours.each_with_index do |tour, index| %>
          <tr>
            <td><%= tour.departure_date.strftime("%d/%m/%Y") %></td>
            <td><%= ((tour.departure_date - @today)/1.day).to_i %></td>
            <td class="code"><div class="trim code"><%= link_to tour.code, admin_tour_path(tour) %></div></td>
            <td class="caption"><div class="trim caption"><%= tour.caption %></div></td>
            <% if tour.is_cruise? %>
              <td><%= tour.all_total_seats %>/(<%= tour.all_total_rooms %>)</td>
              <td><%= tour.all_total_seats - tour.all_vacant_total_seats %>/(<%= tour.all_total_rooms - tour.all_vacant_total_rooms %>)</td>
              <td></td>
              <td></td>
            <% else %>
              <td><%= tour.all_total_seats %></td>
              <td><%= tour.all_total_seats - tour.all_vacant_total_seats %></td>
              <td><%= tour.guaranteed_departure_seats %></td>
              <td><%= tour.guaranteed_departure_seats - (tour.all_total_seats - tour.all_vacant_total_seats) %></td>
            <% end %>
            <td><%= tour.remark %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @tours %>
<% end %>