config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    resources :tours, only: [:index]
    resources :series, only: [:index, :show] do
      collection do
        get 'country_list'
        get 'itinerary_list'
      end
    end
    
    namespace :v1 do
      resources :flights, only: [:index, :show] do
        member do
          post 'create_booking'
        end
        collection do
          get 'bookings'
        end
      end
      resources :activities, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :hotels, only: [:index, :show] do
        collection do
          get 'cities'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'room_policy'
        end
      end
      resources :wifis, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :series, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'itinerary_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          patch 'update_bookings'
          get 'new_payment'
          post 'create_payment'
          post 'create_insurance_export'
        end
      end

      resources :land_tours, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'land_tours_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'new_payment'
          post 'create_payment'
        end
      end

      resources :payments, only: [:show] do
        collection do
          get 'payment_method'
        end
      end

      resources :users, only:[:none] do
        collection do
          get 'details'
          get 'credit_usage'
          get 'credit_packages'
        end
        member do
          post 'purchase_credits'
        end
      end
      
    end

    namespace :tbo_holidays do
      get 'cities' => 'cities#index'
    end
  end

  namespace :admin do
    root to: "sites#dashboard"
    get   '/dashboard'        => 'sites#dashboard', as: :dashboard
    match '/setting_cover'       => 'sites#cover', as: :cover, via: [:get, :post, :delete]

    resources :users, except: [:destroy] do
      member do
        get 'reset_password'
        post 'reset_password'
        get 'edit_password'
        patch 'update_password'
        get 'topup_credits'
        post 'topup_credits'
      end
      collection do
        get 'access_log'
        get 'online_list'
      end
    end

    resources :flight_commissions, except: [:destroy] do
    end

    resources :tour_leaders, expect: [:destroy] do
    end

    resources :tours, except: [:destroy] do
      member do
        post 'create_booking'
        post 'duplicate'
        get 'insurance'
        get 'booking_rooms'
        get 'edit_booking_rooms'
        get 'confirmation'
        patch 'update_booking_rooms'
      end
      collection do
        get 'uncertainty'
        get 'calendar'
      end

    end

    resources :holiday_calendars, except: [:destroy] do 
    end

    resources :flight_booking_groups, only: [:index, :show] do
    end

    resources :hotels, except: [:destroy]

    resources :tbo_hotels, except: [:destroy] do
      member do
        post 'activate'
        post 'deactivate'
      end
    end

    resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:index, :show]

    resources :tbo_bookings, path: 'tbo_bookings', only: [:index, :show] do
      resource :amendment_request, module: :tbo_bookings do
        member do
          post 'widthraw'
        end
      end
      member do
        post 'cancel'
      end
    end

    resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    end

    resources :itineraries do
      member do
        post 'tour_summary'
        post 'duplicate'
      end
      collection do
        get 'tour_status'
      end
    end

    resources :settings do
      collection do
        get 'travelb2b'
        get 'edit_travelb2b'
        post 'update_travelb2b'
      end
    end

    resources :sliders do
    end

    resources :departments, except: [:destroy] do
    end

    resources :etravel_invoices, only: [:index] do
    end
    
    resources :fairs, except: [:destroy] do
    end

    resources :holidays, except: [:destroy] do
    end

    resources :credit_refunds, except: [:destroy] do
      member do
        post 'update_status'
      end
    end

    resources :booking_groups, only: [:index, :show, :edit, :update] do
      member do
        get  'new_alter'
        post 'create_alter'
        get  'new_export'
        post 'create_export'
        post 'create_insurance_export'
        post 'create_insurance_endorse'
        post 'proforma_invoice'
        post 'assign_agent'
      end
      collection do
        get 'received_deposit'
        get 'tour_booking_summary'
        get 'booking_statistic'
        get 'sales_statistic'
        get 'insurance_changes'
      end
    end

    resources :booking_alterations, only: [:index, :show] do
      member do
        get 'restore'
      end
    end

    resources :invoices, only: [:index, :show] do
    end

    get  'search/fair-tag'                => 'sites#fair_tag'
    get  'search/itinerary-tag'           => 'sites#itinerary_tag'
    get  'search/tour-tag'                => 'sites#tour_tag'
    get  'search/user-tag'                => 'sites#user_tag'
    get  'search/country-tag'             => 'sites#country_tag'

    resources :gifts do
      collection do
        get 'gift_stock_report'
      end
    end

    resources :insurance_rebates, only: [:index, :show, :edit, :update] do
    end

    resources :pre_commisions, except: [:destroy] do
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :gift_tracking_groups, except: [:destroy] do
      collection do
        get 'tracking_summary'
      end
      member do
        get 'summary_detail/:id', to: 'gift_tracking_groups#summary_detail', as: 'summary_detail'
        post 'deliver'
      end
    end

    resources :globaltix_tickets do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
    end

    resources :globaltix_attractions do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        # get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
      member do
        post 'add_ticket'
      end
    end

    resources :exchange_rates, except: [:destroy] do
    end

    resources :roamingman_packages, except: [:destroy] do
      member do
        get 'new_booking'
        post 'create_booking'
      end
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :airlines, except: [:destroy] do
    end

    resources :activities, except: [:destroy] do
    end

    resources :flight_inventories, except: [:destroy] do
    end

    resources :activity_booking_groups, except: [:destroy] do
    end

    resources :land_tours, except: [:destroy] do
    end

    resources :cities, except: [:destroy] do
    end

    resources :land_tour_booking_groups, except: [:destroy] do
      member do
        get 'resend_confirmation'
        get  'new_withdraw'
        post 'create_withdraw'
        get 'voucher'
      end
    end
  end

  resources :gift_tracking_groups, except: [:destroy] do
    member do
      post 'submit'
      post 'acknowledge'
      post 'reject'
    end
  end

  resources :hotels, path: 'hotels', only: [:index] do
    collection do
      get   'details'
      get   'booking'
      post  'booking'
    end
  end

  resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:create] do
    member do
      post  'cancel'
    end
  end

  resources :flights, only: [:index, :show] do
    member do
      post 'create_booking'
    end
    collection do
      get 'thankyou'
    end
  end

  resources :flight_booking_groups, only: [:index, :show] do
    member do
      get 'invoice'
    end
  end

  # resources :activities, only: [:index, :show, :create] do
    # resources :activity_bookings, only: [:new, :create] do
    # end

    # collection do
    #   get 'new_booking/:id', to: 'activities#new_booking', as: 'new_booking'
    #   post 'create_booking'
    # end
  # end

  resources :activity_booking_groups, only: [:show, :edit, :update, :index] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :payments, only: [:index] do
    collection do
      get 'error_page'
    end
  end
  
  resources :itineraries do
  end

  resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :roamingman_packages, only: [:index, :show] do
    resources :roamingman_bookings, only: [:new, :create] do
    end
  end

  resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

app/models/roamingman_package.rb
class RoamingmanPackage < ApplicationRecord
  belongs_to :created_user, class_name: "User", optional: true
  belongs_to :last_edited_user, class_name: "User", optional: true
  has_many :roamingman_bookings
  has_many :roamingman_booking_groups, through: :roamingman_bookings
  has_many :covers, as: :taggable
  
  accepts_nested_attributes_for :covers, reject_if: proc { |attributes| attributes['image'].blank? }, allow_destroy: true

  enum category: [:standard, :premium]
  enum status: [:active, :pending]

  scope :search, ->(keyword) { where("roamingman_packages.name ILIKE ? or roamingman_packages.code ILIKE ? or array_to_string(countries, ',') ILIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%") }
  scope :search_country, ->(keyword) { where("array_to_string(countries, ',') ILIKE ?", "%#{keyword}%") }
  scope :visible, -> { where("roamingman_packages.status != ?", RoamingmanPackage.statuses[:pending]) }
  scope :with_visible, -> (only=true) { where("roamingman_packages.status != ?", RoamingmanPackage.statuses[:pending]) if only }

  def join_countries
    if self.countries.present?
      self.countries.join(',')
    else
      ''
    end
  end

  def self.duplicate(package, code, price, type)
    new_package = package.dup
    new_package.code = code
    new_package.retail_price = price
    new_package.package_type = type
    new_package.status = 1

    if new_package.save
      if package.covers.present?
        package.covers.each do |cover|
          if cover.image.present?
            new_package_cover = cover.dup
            new_package_cover.taggable = new_package
            new_package_cover.image = cover.image
            new_package_cover.priority = cover.priority
            new_package_cover.save
          end
        end
      end
    end
    new_package
  end

  def channel_price_markup(user = nil)
    self.channel_price + channel_markup(user)
  end

  def channel_markup(user = nil)
    if user.present? && user.username == "ktic"
      ((self.retail_price - self.channel_price) * 0.2) # 20% markup
    else
      0
    end
  end

  def channel_price=(val)
    if val.present?
      write_attribute(:channel_price, val.to_f.round_to_half(2))
    else
      write_attribute(:channel_price, 0)
    end
  end

  def retail_price=(val)
    if val.present?
      write_attribute(:retail_price, val.to_f.round_to_half(2))
    else
      write_attribute(:retail_price, 0)
    end
  end

  def dta(user = nil)
    if self.retail_price > self.channel_price_markup(user)
      self.retail_price - self.channel_price_markup(user)
    else
      0
    end
  end

end

app/controllers/admin/roamingman_packages_controller.rb
class Admin::RoamingmanPackagesController < AdminController
  before_action :check_auth

  def index
    keywords = params[:keywords].present? ? params[:keywords] : ''
    if params[:only_active_package].present? && params[:only_active_package] == 'false'
      only_active_package = false
    else
      only_active_package = true
    end
    @roamingman_packages = RoamingmanPackage.search(keywords).with_visible(only_active_package).page(params[:page]).per(50)
  end

  def show
    @roamingman_package = RoamingmanPackage.find(params[:id])
    @roamingman_bookings = @roamingman_package.roamingman_bookings.visible.order(created_at: :desc, id: :desc)
  end

  def new
    @roamingman_package = RoamingmanPackage.new
  end

  def create
    @roamingman_package = RoamingmanPackage.new(package_params)
    if @roamingman_package.save
      redirect_to admin_roamingman_packages_path, notice: 'Roamingman Package was successfully created.'
    else
      render :new
    end
  end

  def edit
    @roamingman_package = RoamingmanPackage.find(params[:id])
  end

  def update
    @roamingman_package = RoamingmanPackage.find(params[:id])

    if @roamingman_package.update(package_params)
      redirect_to admin_roamingman_package_path(@roamingman_package), notice: 'Roamingman Package was successfully updated.'
    else
      render :edit
    end
  end

  def new_booking
    @roamingman_package = RoamingmanPackage.find(params[:id])
    @roamingman_booking_group = RoamingmanBookingGroup.new
    @roamingman_booking_group.roamingman_bookings << RoamingmanBooking.new
  end

  def create_booking
    @roamingman_package = RoamingmanPackage.find(params[:id])
    
    @roamingman_booking_group = RoamingmanBookingGroup.new(booking_params)
    if @roamingman_booking_group.save
      if @roamingman_booking_group.export_roamingman_create(current_user)
        redirect_to admin_roamingman_booking_groups_path, notice: 'Roamingman Booking was successfully created and exported.'
      else
        redirect_to admin_roamingman_booking_groups_path, notice: 'Roamingman Booking was failed to export.'
      end
    else
      render :new_booking
    end
  end

private
  def check_auth
    authorize RoamingmanPackage, :index?
  end

  def booking_params
    new_params = params.require(:roamingman_booking_group).permit(:remark, roamingman_bookings_attributes: [:id, :name, :mobile, :email, :depart_date, :return_date, :quantity, :ship_way, :deliver_point_id, :address, :postcode, :is_send_sms, :is_send_email, :_destroy])
    if new_params[:roamingman_bookings_attributes].present?
      new_params[:roamingman_bookings_attributes].each {|k,v| v.merge!(roamingman_package_id: params[:id], agent_user_id: current_user.id)}
    end
    new_params
  end

  def package_params
    params[:roamingman_package][:countries] = params[:roamingman_package][:countries].split(',')
    params.require(:roamingman_package).permit(:code, :name, :category, :package_type, :data_rules, :channel_price, :retail_price, :min_rent_days, :highlight, :status, :terms_and_conditions, countries:[], covers_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/roamingman_packages_controller.rb
class RoamingmanPackagesController < ApplicationController
  def index
    keywords = params[:keywords].present? ? params[:keywords] : ''
    if params[:only_active_package].present? && params[:only_active_package] == 'false'
      only_active_package = false
    else
      only_active_package = true
    end
    @roamingman_packages = RoamingmanPackage.search(keywords).with_visible(only_active_package).page(params[:page]).per(50)
  end

  def show
    @roamingman_package = RoamingmanPackage.find(params[:id])
  end
end

app/views/roamingman_packages/index.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-wifi fa-fw"></i>Roamingman Packages
<% end %>

<%= render 'shared/single_panel', card_title: 'View Roamingman Packages' do %>
  <div class="row">
    <div class="col-xs-12 mt20">
      <%= form_tag roamingman_packages_path, method: 'get' do %>
        <%= text_field_tag :keywords, params[:keywords] %>
        <label class="checkbox-inline">
          <%= hidden_field_tag :only_active_package, 'false' %>
          <%= check_box_tag :only_active_package, 'true', params[:only_active_package].blank? || params[:only_active_package] == 'true' %> Only Active
        </label>
        <%= submit_tag 'Search', class: 'btn btn-success btn-xs' %>
      <% end %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Code</th>
          <th>Name</th>
          <th>Countries & Regions Covered</th>
          <th>Type</th>
          <th class="code">Channel Price (RM)/Day</th>
          <th class="code">Retail Price (RM)/Day</th>
        </tr>
      </thead>
      <tbody>
        <% @roamingman_packages.each do |roamingman_package| %>
          <tr>
            <td><%= roamingman_package.code %></td>
            <td><%= link_to roamingman_package.name, roamingman_package_path(roamingman_package) %></td>
            <td class="caption"><div class="trim caption" data-toggle="tooltip" data-placement="top" title="<%= roamingman_package.join_countries %>"><%= roamingman_package.join_countries %></div></td>
            <td><%= roamingman_package.package_type %></td>
            <td class="code"><%= roamingman_package.channel_price_markup(current_user) %></td>
            <td class="code"><%= roamingman_package.retail_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @roamingman_packages %>
<% end %>

app/views/roamingman_packages/show.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-wifi fa-fw"></i>Roamingman Packages
<% end %>

<%= render 'shared/single_panel', card_title: 'Roamingman Packages Detail' do %>
  <div class="row">
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :code %>
      <%= text_field_tag '', @roamingman_package.code, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :name %>
      <%= text_field_tag '', @roamingman_package.name, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :category %>
      <%= text_field_tag '', @roamingman_package.category.humanize, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :package_type %>
      <%= text_field_tag '', @roamingman_package.package_type, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :data_rules %>
      <%= text_field_tag '', @roamingman_package.data_rules, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :channel_price %>
      <%= text_field_tag '', @roamingman_package.channel_price_markup(current_user), class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :retail_price %>
      <%= text_field_tag '', @roamingman_package.retail_price, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :min_rent_days %>
      <%= text_field_tag '', @roamingman_package.min_rent_days, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :highlight %>
      <%= text_field_tag '', @roamingman_package.highlight, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :status %>
      <%= text_field_tag '', @roamingman_package.status.humanize, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag :countries, "Countries & Regions Covered" %>
      <%= text_area_tag '', @roamingman_package.join_countries, class: 'form-control', rows: "3", disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag :terms_and_conditions %>
      <%= text_area_tag '', @roamingman_package.terms_and_conditions, class: 'form-control', rows: "4", disabled: true %>
    </div>
  </div>
  <% if policy(RoamingmanBooking).new? && @roamingman_package.active? %>
    <%= link_to 'Add Booking', new_roamingman_package_roamingman_booking_path(@roamingman_package), class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Cancel', :back, class: 'btn' %>
<% end %>