config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users

  namespace :api, defaults: {format: 'json'} do
    resources :tours, only: [:index]
    resources :series, only: [:index, :show] do
      collection do
        get 'country_list'
        get 'itinerary_list'
      end
    end
    
    namespace :v1 do
      resources :flights, only: [:index, :show] do
        member do
          post 'create_booking'
        end
        collection do
          get 'bookings'
        end
      end
      resources :activities, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :hotels, only: [:index, :show] do
        collection do
          get 'cities'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'room_policy'
        end
      end
      resources :wifis, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
        end
      end
      resources :series, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'itinerary_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          patch 'update_bookings'
          get 'new_payment'
          post 'create_payment'
          post 'create_insurance_export'
        end
      end

      resources :land_tours, only: [:index, :show] do
        collection do
          get 'country_list'
          get 'land_tours_list'
          get 'designation_list'
          get 'bookings'
        end
        member do
          post 'create_booking'
          get 'new_payment'
          post 'create_payment'
        end
      end

      resources :payments, only: [:show] do
        collection do
          get 'payment_method'
        end
      end

      resources :users, only:[:none] do
        collection do
          get 'details'
          get 'credit_usage'
          get 'credit_packages'
        end
        member do
          post 'purchase_credits'
        end
      end
      
    end

    namespace :tbo_holidays do
      get 'cities' => 'cities#index'
    end
  end

  namespace :admin do
    root to: "sites#dashboard"
    get   '/dashboard'        => 'sites#dashboard', as: :dashboard
    match '/setting_cover'       => 'sites#cover', as: :cover, via: [:get, :post, :delete]

    resources :users, except: [:destroy] do
      member do
        get 'reset_password'
        post 'reset_password'
        get 'edit_password'
        patch 'update_password'
        get 'topup_credits'
        post 'topup_credits'
      end
      collection do
        get 'access_log'
        get 'online_list'
      end
    end

    resources :flight_commissions, except: [:destroy] do
    end

    resources :tour_leaders, expect: [:destroy] do
    end

    resources :tours, except: [:destroy] do
      member do
        post 'create_booking'
        post 'duplicate'
        get 'insurance'
        get 'booking_rooms'
        get 'edit_booking_rooms'
        get 'confirmation'
        patch 'update_booking_rooms'
      end
      collection do
        get 'uncertainty'
        get 'calendar'
      end

    end

    resources :holiday_calendars, except: [:destroy] do 
    end

    resources :flight_booking_groups, only: [:index, :show] do
    end

    resources :hotels, except: [:destroy]

    resources :tbo_hotels, except: [:destroy] do
      member do
        post 'activate'
        post 'deactivate'
      end
    end

    resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:index, :show]

    resources :tbo_bookings, path: 'tbo_bookings', only: [:index, :show] do
      resource :amendment_request, module: :tbo_bookings do
        member do
          post 'widthraw'
        end
      end
      member do
        post 'cancel'
      end
    end

    resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    end

    resources :itineraries do
      member do
        post 'tour_summary'
        post 'duplicate'
      end
      collection do
        get 'tour_status'
      end
    end

    resources :settings do
      collection do
        get 'travelb2b'
        get 'edit_travelb2b'
        post 'update_travelb2b'
      end
    end

    resources :sliders do
    end

    resources :departments, except: [:destroy] do
    end

    resources :etravel_invoices, only: [:index] do
    end
    
    resources :fairs, except: [:destroy] do
    end

    resources :holidays, except: [:destroy] do
    end

    resources :credit_refunds, except: [:destroy] do
      member do
        post 'update_status'
      end
    end

    resources :booking_groups, only: [:index, :show, :edit, :update] do
      member do
        get  'new_alter'
        post 'create_alter'
        get  'new_export'
        post 'create_export'
        post 'create_insurance_export'
        post 'create_insurance_endorse'
        post 'proforma_invoice'
        post 'assign_agent'
      end
      collection do
        get 'received_deposit'
        get 'tour_booking_summary'
        get 'booking_statistic'
        get 'sales_statistic'
        get 'insurance_changes'
      end
    end

    resources :booking_alterations, only: [:index, :show] do
      member do
        get 'restore'
      end
    end

    resources :invoices, only: [:index, :show] do
    end

    get  'search/fair-tag'                => 'sites#fair_tag'
    get  'search/itinerary-tag'           => 'sites#itinerary_tag'
    get  'search/tour-tag'                => 'sites#tour_tag'
    get  'search/user-tag'                => 'sites#user_tag'
    get  'search/country-tag'             => 'sites#country_tag'

    resources :gifts do
      collection do
        get 'gift_stock_report'
      end
    end

    resources :insurance_rebates, only: [:index, :show, :edit, :update] do
    end

    resources :pre_commisions, except: [:destroy] do
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :gift_tracking_groups, except: [:destroy] do
      collection do
        get 'tracking_summary'
      end
      member do
        get 'summary_detail/:id', to: 'gift_tracking_groups#summary_detail', as: 'summary_detail'
        post 'deliver'
      end
    end

    resources :globaltix_tickets do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
    end

    resources :globaltix_attractions do
      collection do
        get 'select', constraints: { country_id: /[0-9]*/, page: /[0-9]*/ }
        # get 'activities', constraints: { attraction_id: /[0-9]*/ }
      end
      member do
        post 'add_ticket'
      end
    end

    resources :exchange_rates, except: [:destroy] do
    end

    resources :roamingman_packages, except: [:destroy] do
      member do
        get 'new_booking'
        post 'create_booking'
      end
    end

    resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    end

    resources :airlines, except: [:destroy] do
    end

    resources :activities, except: [:destroy] do
    end

    resources :flight_inventories, except: [:destroy] do
    end

    resources :activity_booking_groups, except: [:destroy] do
    end

    resources :land_tours, except: [:destroy] do
    end

    resources :cities, except: [:destroy] do
    end

    resources :land_tour_booking_groups, except: [:destroy] do
      member do
        get 'resend_confirmation'
        get  'new_withdraw'
        post 'create_withdraw'
        get 'voucher'
      end
    end
  end

  resources :gift_tracking_groups, except: [:destroy] do
    member do
      post 'submit'
      post 'acknowledge'
      post 'reject'
    end
  end

  resources :hotels, path: 'hotels', only: [:index] do
    collection do
      get   'details'
      get   'booking'
      post  'booking'
    end
  end

  resources :hotel_booking_groups, path: 'hotel_booking_groups', only: [:create] do
    member do
      post  'cancel'
    end
  end

  resources :flights, only: [:index, :show] do
    member do
      post 'create_booking'
    end
    collection do
      get 'thankyou'
    end
  end

  resources :flight_booking_groups, only: [:index, :show] do
    member do
      get 'invoice'
    end
  end

  # resources :activities, only: [:index, :show, :create] do
    # resources :activity_bookings, only: [:new, :create] do
    # end

    # collection do
    #   get 'new_booking/:id', to: 'activities#new_booking', as: 'new_booking'
    #   post 'create_booking'
    # end
  # end

  resources :activity_booking_groups, only: [:show, :edit, :update, :index] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :payments, only: [:index] do
    collection do
      get 'error_page'
    end
  end
  
  resources :itineraries do
  end

  resources :globaltix_ticket_booking_groups, path: 'ticket_booking_groups', only: [:index, :show] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

  resources :roamingman_packages, only: [:index, :show] do
    resources :roamingman_bookings, only: [:new, :create] do
    end
  end

  resources :roamingman_booking_groups, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'thank_you'
    end
    member do
      get 'invoice'
    end
  end

app/models/globaltix_ticket.rb
class GlobaltixTicket < ApplicationRecord
  enum markup_category: [:percentage, :fixed]
  enum status: [:pending, :active, :archived, :n_a]

  belongs_to :globaltix_attraction
  validates :ticket_id, uniqueness: true

  scope :countries, -> { distinct.pluck(:country) }
  scope :search_status, ->(status) { where("status = ?", GlobaltixTicket.statuses[status]) if status.present? }
  scope :search_keyword, ->(keyword) { where("country ILIKE :keyword OR title ILIKE :keyword", keyword: "%#{keyword}%")  if keyword.present? }
  scope :search_country, ->(keyword) { where("country ILIKE ?", keyword) if keyword.present? }
  scope :search_title, ->(keyword) { where("title ILIKE ?", "%#{keyword}%") if keyword.present? }
  scope :order_by_priority, -> { order("priority ASC") }

  has_many :covers, as: :taggable
  
  accepts_nested_attributes_for :covers, reject_if: proc { |attributes| attributes['image'].blank? }, allow_destroy: true

  typed_store :details, coder: PostgresCoder do |s|
    # s.string :title, default: ''
    s.string :name, default: ''
    s.string :currency, default: ''
    s.decimal :price, default: 0
    s.string :variation, default: ''
  end

  SGD_CONVERTED_TO_MYR = 3.0

  def final_price(minus_dta = false)
    price_in_myr
    if minus_dta
      price_in_myr
    else
      price_in_myr + self.dta
    end
  end

  def price_in_myr
    if currency == 'SGD'
      rate = ExchangeRate.find_by(from_currency: 'SGD', to_currency: 'MYR').try(:rate) || GlobaltixTicket::SGD_CONVERTED_TO_MYR
      myr_price = price * rate
      if markup.present?
        if self.percentage?
          myr_price = myr_price * (1 + markup / 100)
        elsif self.fixed?
          myr_price = myr_price + markup
        end
      end
      myr_price.ceil
    else
      nil
    end    
  end

  def dta
    if self.price_in_myr.present?
      (self.price_in_myr * (Setting.activity_dta_markup.to_f / 100.to_f)).round_to_half(2)
    else
      0
    end
  end

  # def dta_amount
  #   (self.final_price * (Setting.activity_dta_markup.to_f / 100.to_f)).round
  # end

  # def self.dta_min_price(tickets = [])
  #   (self.min_price(tickets) * (1 + Setting.activity_dta_markup.to_f / 100.to_f)).round
  # end

  # def self.min_price(tickets = [])
  #   tickets.map { |d| d.final_price }.min
  # end

  def markup_display
    if self.markup.present?
      if self.percentage?
        '+' + self.markup.to_s + '%'
      elsif self.fixed?
        '+' + self.markup.to_s
      else
        ''
      end
    else
      ''
    end
  end

  def ticket
    ticket, ticket_err = Globaltix::Ticket.find(self.ticket_id)
    ticket
  end

  def title_name
    "#{self.title}-#{self.name}"
  end

  def self.create_ticket(globaltix_ticket_id)
    @ticket, ticket_err = Globaltix::Ticket.find(globaltix_ticket_id)
    @globaltix_attraction = GlobaltixAttraction.find_by_attraction_id(@ticket.attraction.id)
    ticket = self.new(ticket_id: @ticket.id, globaltix_attraction_id: @globaltix_attraction.id, attraction_id: @ticket.attraction.id, title: @ticket.attraction.title, name: @ticket.name, variation: @ticket.variation, currency: @ticket.currency, price: @ticket.settlement_rate, country: @ticket.country, description: @ticket.description, terms_and_conditions: @ticket.terms_and_conditions)
    ticket.save
    ticket
  end

  def blockout_dates_text
    if blockout_dates.present?
      blockout_dates.map{|blockout_date| "#{blockout_date.begin.strftime("%d/%m/%Y")}-#{blockout_date.max.strftime("%d/%m/%Y")}"}.join(', ')
    else
      ""
    end
  end

  def blockout_dates_text=(val)
    dates_text = val.split(',')
    all_date = []
    dates_text.each do |date_text|
      date_text_start, date_text_end = date_text.split('-')

      date_start = Date.parse(date_text_start) rescue nil
      date_end = Date.parse(date_text_end) rescue nil

      if date_start.present? && date_end.present?
        all_date << Range.new(date_start, date_end)
      end
    end

    write_attribute(:blockout_dates,all_date)
  end

end

app/controllers/admin/globaltix_tickets_controller.rb
class Admin::GlobaltixTicketsController < AdminController
  before_action :check_auth
  def index
    @globaltix_tickets = GlobaltixTicket.search_status(params[:status])
  end

  def select
    @countries, countries_err = Globaltix::Country.all

    if params[:country_id].blank?
      params[:country_id] = 1
    end
    if params[:page].blank?
      params[:page] = 1
    end

    if params[:keyword].present?
      @attractions, attractions_err = Globaltix::Attraction.where(countryId: params[:country_id], page: params[:page], keyword: params[:keyword], field: :title)
    else
      @attractions, attractions_err = Globaltix::Attraction.where(countryId: params[:country_id], page: params[:page])
    end
  end

  def activities
    @tickets, tickets_err = Globaltix::Ticket.where(attraction_id: params[:attraction_id])
    render json: { html: helpers.render_admin_activity_tickets(@tickets) }
  end

  def new
    @ticket, ticket_err = Globaltix::Ticket.find(params[:ticket_id])
    @globaltix_attraction = GlobaltixAttraction.find_by_attraction_id(@ticket.attraction.id)
    @globaltix_ticket = GlobaltixTicket.new
  end

  def create
    @globaltix_ticket = GlobaltixTicket.new(globaltix_ticket_params)

    if @globaltix_ticket.save
      redirect_to admin_globaltix_tickets_path, notice: 'Globaltix ticket was successfully created.'
    else
      @ticket, ticket_err = Globaltix::Ticket.find(params[:globaltix_ticket][:ticket_id])
      render :new
    end
  end

  def show
    @globaltix_ticket = GlobaltixTicket.find(params[:id])
    @globaltix_attraction = GlobaltixAttraction.find_by_attraction_id(@globaltix_ticket.attraction_id)
  end

  def edit
    @globaltix_ticket = GlobaltixTicket.find(params[:id])
    @globaltix_attraction = GlobaltixAttraction.find_by_attraction_id(@globaltix_ticket.attraction_id)
  end

  def update
    @globaltix_ticket = GlobaltixTicket.find(params[:id])

    if @globaltix_ticket.update(globaltix_ticket_params)
      redirect_to admin_globaltix_tickets_path(@globaltix_ticket), notice: 'Globaltix ticket was successfully updated.'
    else
      render :edit
    end
  end



private
  def globaltix_ticket_params
    params.require(:globaltix_ticket).permit(:ticket_id, :attraction_id, :title, :name, :variation, :country, :currency, :price, :markup_category, :markup, :remark, :status, :globaltix_attraction_id, covers_attributes: [:id, :image, :_destroy])
  end

  def check_auth
    authorize GlobaltixTicket, :index?
  end
end

app/views/admin/globaltix_tickets/_cover_fields.html.erb
<div class="nested-fields">
  <% if f.object.image.present? %>
    <%= link_to f.object.image.url, target: '_blank' do %>
      <% image_tag f.object.image.url, class: 'cover-thumbnail' %>
    <% end %>
  <% else %>
  <div class="field custom-form-group form-group col-sm-12">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'custom-form-control form-control' %>
  </div>
  <% end %>
  <%= link_to_remove_association "Remove Image", f %>
</div>

app/views/admin/globaltix_tickets/edit.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-ticket fa-fw"></i>Globaltix Tickets
<% end %>

<%= render 'shared/single_panel', card_title: 'Edit Globaltix Ticket' do %>
<div class="table-responsive">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Attraction id</th>
          <th>Country</th>
          <th>Title</th>
          <th>Description</th>
          <th>Hours of operation</th>
          <th>Term and condition</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @globaltix_attraction.attraction_id %></td>
            <td><%= @globaltix_attraction.country %></td>
            <td><%= @globaltix_attraction.title.truncate(50) %></td>
            <td><%= @globaltix_attraction.description.truncate(50) %></td>
            <td><%= @globaltix_attraction.hours_of_operation.truncate(50) %></td>
            <td><%= @globaltix_attraction.term_and_condition.truncate(50) %></td>
          </tr>
      </tbody>
    </table>
  </div>
  <%= form_for [:admin, @globaltix_ticket], html: { role: "form" } do |f| %>
    <%= render partial: 'partials/errors', locals: { target: @globaltix_ticket } %>
    <div class="row">
      <%= f.hidden_field :ticket_id %>
      <%= f.hidden_field :attraction_id %>
      <%= f.hidden_field :globaltix_attraction_id %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :currency %>
      <%= f.hidden_field :price %>
      <%= f.hidden_field :variation %>
      <%= f.hidden_field :country %>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'custom-form-control form-control', disabled: true %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'custom-form-control form-control', disabled: true %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :variation %>
        <%= f.text_field :variation, class: 'custom-form-control form-control', disabled: true %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :country %>
        <%= f.text_field :country, class: 'custom-form-control form-control', disabled: true %>
      </div>
    </div>
    <div class="row">
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :currency %>
        <%= f.text_field :currency, class: 'custom-form-control form-control', disabled: true %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'custom-form-control form-control', disabled: true %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :markup_category %>
        <%= f.select :markup_category, options_for_select(GlobaltixTicket.markup_categories.collect { |s| [s[0], s[0]] }, selected: @globaltix_ticket.markup_category), {include_blank: true}, {class: 'custom-form-control form-control' } %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :markup %>
        <%= f.number_field :markup, class: 'custom-form-control form-control', step: :any %>
      </div>
      <div class="custom-form-group form-group col-sm-12">
        <%= f.label :remark %>
        <%= f.text_area :remark, class: 'form-control', rows: "3" %>
      </div>
      <div class="custom-form-group form-group col-sm-6">
        <%= f.label :status %>
        <%= f.select :status, options_for_select(GlobaltixTicket.statuses.collect { |s| [s[0], s[0]] }, selected: @globaltix_ticket.status), {include_blank: true}, {class: 'custom-form-control form-control' } %>
      </div>
      <!-- <div class="custom-form-group form-group col-sm-12">
      <%= f.label :covers, "Images" %>
      <%= f.fields_for :covers do |cover| %>
        <%= render 'cover_fields', f: cover %>
      <% end %>
      <div class="custom-form-group form-group col-sm-12">
        <%= link_to_add_association 'Add Image', f, :covers %>
      </div> 
    </div> -->
    <div class="custom-form-group form-group col-sm-12">
      <%= f.submit "Update", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', :back, class: 'btn' %>
    </div>
  <% end %>
<% end %>

app/views/admin/globaltix_tickets/index.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-ticket fa-fw"></i>Globaltix Tickets
<% end %>

<%= render 'shared/single_panel', card_title: 'View Globaltix Tickets' do %>
  <div class="row">
    <div class="col-xs-12 mt20 mb20">
      <%= form_tag admin_globaltix_tickets_path, method: 'get' do %>
        <%= select_tag :status, options_for_select(GlobaltixTicket.statuses.collect { |s| [s[0].humanize, s[0]] }, params[:status]), {include_blank: true} %>
        <%= submit_tag 'Search', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Attraction</th>
          <th>Name</th>
          <th>Price</th>
          <th>Markup</th>
          <th>Final Price</th>
          <th>Remark</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @globaltix_tickets.each do |globaltix_ticket| %>
          <tr>
            <td><%= globaltix_ticket.title %></td>
            <td><%= link_to globaltix_ticket.name, admin_globaltix_ticket_path(globaltix_ticket) %></td>
            <td><%= "#{globaltix_ticket.currency}#{globaltix_ticket.price}" %></td>
            <td><%= globaltix_ticket.markup_display %></td>
            <td>MYR<%= globaltix_ticket.final_price %></td>
            <td><%= globaltix_ticket.remark %></td>
            <td><%= globaltix_ticket.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admin/globaltix_tickets/select.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-ticket fa-fw"></i>Globaltix Activities
<% end %>

<%= render 'shared/single_panel', card_title: 'Select Activities' do %>
  <div class="row">
    <div class="col-xs-12 mt20">
      <%= form_tag(select_admin_globaltix_tickets_path, method: :get)do %>
        <div class="row">
          <div class="custom-form-group form-group col-sm-3">
            <%= label_tag(:country) %>
            <%= select_tag(:country_id, options_for_select(@countries.collect {|s| [s.name, s.id]}, selected: params[:country_id]), {class: 'custom-form-control form-control'})%>
          </div>
          <div class="custom-form-group form-group col-sm-3">
            <%= label_tag(:keyword) %>
            <%= text_field_tag :keyword, params[:keyword],  {class: 'custom-form-control form-control'}  %>
          </div>
        </div>
        <%= submit_tag 'Search', class: 'btn btn-success btn-xs' %>
      <% end %>
    </div>
  </div>
  <% if @attractions.present? %>
    <div class="row">
      <div class="col-xs-12 mt20">
        <% @attractions.each do |attraction| %>
          <div class="panel panel-default">
            <a data-toggle="collapse" href='#<%= "attraction-#{attraction.id}" %>'>
              <div class="panel-heading">
                <div class="attraction-img-div">
                  <%= image_tag attraction.image_url(:thumb), class: "attraction-img" %>
                </div>
                <div class="attraction-title">
                  <h4 class="panel-title"><%= attraction.title %></h4>
                </div>
              </div>
            </a>
            <div id='<%= "attraction-#{attraction.id}" %>' class="panel-collapse collapse attraction-collapse">
              <div class="panel-body activities-empty" data-url="<%= activities_admin_globaltix_tickets_path(attraction_id: attraction.id) %>">

                Loading activities...
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= paginate @attractions %>
<% end %>

app/views/admin/globaltix_tickets/show.html.erb
<% content_for :head do %>
  <title><%= @app_name %></title>
<% end %>

<% content_for :title do %>
  <i class="fa fa-ticket fa-fw"></i>Globaltix Tickets
<% end %>

<%= render 'shared/single_panel', card_title: 'Globaltix Ticket Detail' do %>
<div class="table-responsive">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Attraction id</th>
          <th>Country</th>
          <th>Title</th>
          <th>Description</th>
          <th>Hours of operation</th>
          <th>Term and condition</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @globaltix_attraction.attraction_id %></td>
            <td><%= @globaltix_attraction.country %></td>
            <td><%= @globaltix_attraction.title.truncate(50) %></td>
            <td><%= @globaltix_attraction.description.truncate(50) %></td>
            <td><%= @globaltix_attraction.hours_of_operation.truncate(50) %></td>
            <td><%= @globaltix_attraction.term_and_condition.truncate(50) %></td>
          </tr>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :title %>
      <%= text_field_tag '', @globaltix_ticket.title, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :name %>
      <%= text_field_tag '', @globaltix_ticket.name, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :variation %>
      <%= text_field_tag '', @globaltix_ticket.variation, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :country %>
      <%= text_field_tag '', @globaltix_ticket.country, class: 'custom-form-control form-control', disabled: true %>
    </div>
  </div>
  <div class="row">
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :currency %>
      <%= text_field_tag '', @globaltix_ticket.currency, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :price %>
      <%= text_field_tag '', @globaltix_ticket.price, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :markup_category %>
      <%= text_field_tag '', @globaltix_ticket.markup_category, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :markup %>
      <%= text_field_tag '', @globaltix_ticket.markup, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :final_price %>
      <%= text_field_tag '', @globaltix_ticket.final_price, class: 'custom-form-control form-control', disabled: true %>
    </div>
  </div>
  <div class="row">
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :remark %>
      <%= text_field_tag '', @globaltix_ticket.remark, class: 'custom-form-control form-control', disabled: true %>
    </div>
    <div class="custom-form-group form-group col-sm-6">
      <%= label_tag :status %>
      <%= text_field_tag '', @globaltix_ticket.status, class: 'custom-form-control form-control', disabled: true %>
    </div>
  </div>
  <!-- <div class="row">
    <div class="custom-form-group form-group col-sm-12">
      <%= label_tag '', "Images" %><br>
      <% @globaltix_ticket.covers.each do |cover| %>
        <% if cover.image.present? %>
          <div class="custom-form-group form-group col-sm-4">
            <%= link_to cover.image.url, target: '_blank' do %>
              <% image_tag cover.image.url, class: 'cover-thumbnail' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div> -->

  <%= link_to 'Edit', edit_admin_globaltix_ticket_path(@globaltix_ticket), class: 'btn btn-primary' %>
  <%= link_to 'Cancel', :back, class: 'btn' %>
<% end %>